---
title: "1.1 Probability Space"
author: "Luning Li"
date: "2020/10/3"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.1.1

(i) If $\mathcal{F}_i$, $i\in I$ are $\sigma$-fields, then $\bigcap_{i\in I}\mathcal{F}_i$ is. Here $I = \emptyset$ is an
arbitrary index set (i.e., possibly uncountable). (ii) Use the result in (i) to show that
if we are given a set $\Omega$ and a collection A of subsets of $\mathcal{A}$, then there is a smallest
$\sigma$-field containing $\mathcal{A}$. We will call this the $\sigma$-field generated by $\mathcal{A}$ and denote it
by $\sigma(\mathcal{A})$.

(i) Denote $\mathcal{F}:=\bigcap_{i\in I}\mathcal{F}_i$. 

Take $A\in \mathcal{F}$, then $A\in \mathcal{F}_i$ for all $i=1,2,\ldots$. Then $A^C\in \mathcal{F}_i$ for all $i=1,2,\ldots$, because $\mathcal{F}_i$'s are $\sigma$-fields. Therefore, $A^C\in \bigcap_{i\in I}\mathcal{F}_i=\mathcal{F}$.

Take a countable sequence of sets $A_j\in \mathcal{F}$ for $j=1,2,\ldots$, then $A_j\in \mathcal{F}_i$ for all $i=1,2,\ldots$ and $j=1,2,\ldots$. Then $\bigcup_j A_j\in \mathcal{F}_i$ for $i=1,2,\ldots$. Therefore, $\bigcup_j A_j\in \bigcap_i\mathcal{F}_i=\mathcal{F}$.

Then we can conclude that $\mathcal{F}$ is a $\sigma$-field.

(ii) Define $\mathcal{F}$ to be the intersection of all $\sigma$-field that contains $\mathcal{A}$. Then by (i), $\mathcal{F}$ is a $\sigma$-field. And by its definition, every $\sigma$-field that contains $\mathcal{F}$ contains $\mathcal{F}$. That means: $\mathcal{F}$ is the smallest $\sigma$-field containing $\mathcal{A}$.

## 1.1.2

Let $\Omega = \mathbb{R}$,$\mathcal{F} =$ all subsets so that $A$ or $A^C$ is countable, $P(A) = 0$ in the
first case and $= 1$ in the second. Show that $(\Omega,\mathcal{F}, P)$ is a probability space.

Proof: First we show that $\mathcal{F}$ is a $\sigma$-field:

Take $A\in \mathcal{F}$, then $A=(A^C)^C$ or $A$ is countable. This means that $A^C\in \mathcal{F}$.

Take a countable sequence of sets $A_i\in \mathcal{F}$ for all $i=1,2,\dots$. Then either $A_i$ or $A_i^C$ is countable. If all $A_i$'s are countable, then $\bigcup_i A_i$ is countable, because countable union of countable sets is still countable. Otherwise, there exists uncountable $A_j$ for some $j$, then we have $A_j^C$ is countable. Then $(\bigcup_i A_i)^C=\bigcap_i A_i^C\subset A_j^C$ is countable. Then $\bigcup_i A_i\in \mathcal{F}$.

Therefore, $\mathcal{F}$ is a $\sigma$-field.

Second, we show that $P$ is a measure:

For any $A\in \mathcal{F}$, $P(A)\geq 0=P(\emptyset)$ by the definition of $P$. Take a countable sequence of disjoint sets $A_i\in \mathcal{F}$. If all $A_i$'s are countable, then $\bigcup_i A_i$ is also countable. Then $P(\bigcup_i A_i)=0$, and $P(A_i)=0$ for all $i$. Therefore, we have $P(\bigcup_iA_i)=0=\sum_iP(A_i)$. Otherwise, there exists an uncountable $A_j$ for some $j$. Because $A_i$'s are disjoint, $A_i\subset A_j^C$ for all $i\neq j$. $A_j\in \mathcal{F}$ and $A_j$ is uncountable, then $A_j^C$ is countable. Then $A_i\subset A_j^C$ is countable for all $i\neq j$, which means that $P(A_j)=1$ and $P(A_i)=0$ for all $i\neq j$. Moreover, we have $A_j\subset \bigcup_i A_i$, and therefore, $\bigcup_i A_i$ is uncountable, and then $P(\bigcup_i A_i)=1$. Then we have $P(\bigcup_i A_i)=1=1+0=P(A_j)+\sum_{i\neq j}P(A_i)=\sum_i P(A_i)$.

Therefore, $P$ is a measure with $P(\Omega)=P(\mathbb{R})=1$. Then $P$ is a probability.

## 1.1.3 

Let $\mathcal{S}_d$ be the empty set plus all sets of the form $(a_i,b_1]\times \ldots \times (a_d,b_d]$ where $-\infty\leq a_i<b_i\le \infty$. Show that $\sigma(\mathcal{S}_d)=\mathcal{R}_d$.

Proof: 
Before I prove this problem, i would like to prove the following lemma:
$(a_1,b_1)\times \ldots \times (a_d,b_d)$ where $-\infty\leq a_i<b_i\le \infty$ generates $\mathcal{R}^d$.

proof of the lemma:

Denote $\mathcal{F}$ as the $\sigma$-algebra generated by $(a_1,b_1)\times \ldots \times (a_d,b_d)$ where $-\infty\leq a_i<b_i\le \infty$. Then easy to show that $\mathcal{F}\subset \mathcal{R}^d$. For an open set $A\in \mathbb{R}^d$, and any point $x\in A$, we know there exists rational numbers $a_1^x,\ldots,a_d^x,b_1^x,\ldots,b_d^x$ such that $x\in (a_1^x,b_1^x)\times \ldots \times (a_d^x,b_d^x)\subset A$. Then $A=\bigcup_{x\in A} (a_1^x,b_1^x)\times \ldots \times (a_d^x,b_d^x)$ and there are only countably many sets of the form $(a_1^x,b_1^x)\times \ldots \times (a_d^x,b_d^x)$, which means $A$ is a countable union of sets of form $(a_1,b_1)\times \ldots \times (a_d,b_d)$. Therefore, $A\in \mathcal{F}$. Together with definition of $\mathcal{R}^d$(the $\sigma$-algebra generated by all open sets in $\mathbb{R}^d$), we have $\mathcal{R}^d\subset \mathcal{F}$. In conclusion, $\mathcal{F}=\mathcal{R}^d$.

Proof of the problem:

First note that  $(a_1,b_1]\times \ldots \times (a_d,b_d]= (a_1,b_1+1)\times \ldots \times (a_d,b_d+1)\cap (b_1,b_1+1)\times \ldots \times (b_d,b_d+1)$. The latter two sets are open set, so they are in $\mathcal{R}^d$; therefore, we can conclude that their intersection  $(a_i,b_1]\times \ldots \times (a_d,b_d]\in \mathcal{R}^d$. So $\sigma(\mathcal{S}^d)\subset \mathcal{R}^d$. Second, for an arbitrary given open interval $(a,b)$, we can write $(a,b)=\bigcup_{n=1}^{\infty} (a,b-\frac{1}{n}]\in \sigma(\mathcal{S}^d)$. All open intervals generates $\mathcal{R}^d$. So $\mathcal{R}^d\subset \sigma(\mathcal {S}^d)$. Then we can conclude that $\sigma(\mathcal{S}^d)=\mathcal{R}^d$. 

## 1.1.4

A $\sigma$-field $\mathcal{F}$ is said to be countably generated if there is a countable collection $\mathcal{C}\subset \mathcal{F}$ so that $\sigma(\mathcal{C}) = \mathcal{F}$. Show that $\mathcal{R}^d$ is countably generated.

Proof: Idea: show that $\mathcal{R}^d$ is generated by $(a_i,b_1]\times \ldots \times (a_d,b_d]$ where $-\infty\leq a_i<b_i\le \infty$ and $a_i,b_i\in \mathbb{Q}$. Detail proof please refer to file Homework1.pdf.

## 1.1.5

(i) Show that if $\mathcal{F}_1\subset \mathcal{F}_2 \subset \ldots$ are $\sigma$-algebras, then $\cup_i\mathcal{F}_i$ is an algebra. 

(ii) Give an example to show that $\cup_i\mathcal{F}_i$ need not be a $\sigma$-algebra.

Proof: 

(i) Take $A\in \cup_i\mathcal{F}_i$, then $A\in \mathcal{F}_i$ for some $i$. $\mathcal{F}_i$ is a $\sigma$-algebra, therefore, $A^c\in \mathcal{F}_i\subset \cup_i\mathcal{F}_i$. Take a finite sequence of sets $A_1,A_2,\ldots,A_n\subset \cup_i\mathcal{F}_i$. Then for each $i$ in {$1,2,\dots,n$}, $A_i\in \mathcal{F}_{k_i}$ for some $k_i$. Take $k=max\{k_1,\ldots,k_n\}$, then $A_i\in \mathcal{F}_k$ for all $i$. Then $\bigcup_i A_i\in \mathcal{F}_k\subset \cup_i\mathcal{F}_i$. Therefore, $\cup_i\mathcal{F}_i$ is an algebra.

(ii) We define the $\sigma$-algebra $\mathcal{F}_i$ to be the $\sigma$-algebra generated by all the open sets in $[\frac{1}{i},1]$. Then clearly we have $\mathcal{F}_1\subset \mathcal{F}_2 \subset \ldots$. Take $A_i=(\frac{1}{i},1)\in \mathcal{F}_i$. Then $A_i\in \bigcup_n \mathcal{F}_n$ for all $i$. But $\bigcup_i A_i=(0,1)\notin \mathcal{F}_n$ for any $n$. Therefore, $\bigcup_i A_i=(0,1)\notin \bigcup_n \mathcal{F}_n$, which means that $\cup_i\mathcal{F}_i$ is not a $\sigma$-algebra.

## 1.1.6

1.1.6. A set $\mathcal{A} \subset \{1, 2,\ldots\}$ is said to have asymptotic density $\theta$ if $\lim_{n\rightarrow \infty} \mid A \cap \{1, 2,\ldots,n\}\mid /n = \theta$. Let $\mathcal{A}$ be the collection of sets for which the asymptotic density exists. Is $\mathcal{A}$ a $\sigma$-algebra? an algebra?

Proof: It is not even an algebra. Let's assume that $C_k=[2^k,2^{k+1}]$ for $k=0,1,\ldots$. Define $A$ be the set of all odd numbers in $C_k$ for odd $k$ and all even numbers in $C_k$ for even $k$. Then $\lim_{n\rightarrow \infty} \mid A \cap \{1, 2,\ldots,n\}\mid /n = \frac{1}{2}$. Let $B=\{2,4,6,\ldots\}$, then $\lim_{n\rightarrow \infty} \mid B \cap \{1, 2,\ldots,n\}\mid /n = \frac{1}{2}$. Now consider $A\cap B$: This is the set of all even numbers in $[2^{2k},2^{2k+1}]$. In each interval like this, there are $2^k+1$ even numbers. If $n$ approaches $\infty$ in form of $2^{2k+1}$, then this limit turns to be $\frac{1}{3}$; and if $n$ approaches $\infty$ in form of $2^{2k}$, this limit turns to be $\frac{1}{6}$. This means this limit must diverge. i.e. $A\cap B$ does not have asymptotic density. Therefore, our set is not closed under finite intersection, it cannot be an algebra.


Finished.























